# Generated by Django 4.1.1 on 2022-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_booking_bookingslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='company_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
