# Generated by Django 4.1.1 on 2022-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_booking_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
